### ISSUE TITLE
EnvyUpdate doesn't understand Nvidia Hotfix drivers.

### ISSUE THREAD

**Issue by Primeey** [fyr77/EnvyUpdate#15]
Whenever you have the latest Hotfix driver installed (451.85 currently) EnvyUpdate still tells you your driver is out of date and prompts you to download a older version (451.67 currently).

**Comment by fyr77** [comment]
Oh, interesting... 
Can you tell me which GPU you're using?

**Comment by fyr77** [comment]
I don't quite know where I should get info about hotfix drivers from. Visiting the website and trying to download drivers still gives me 451.67... Is there a page that shows me the newest hotfix driver version?

**Comment by fyr77** [comment]
For now I will fix this by comparing driver versions as a number. So using a newer driver than the website states will not alert.

**Comment by fyr77** [comment]
Workaround implemented in commit fff0d76b83fdbc247433031c537a797f1a53539e and it will be implemented in the next versioned release.

**Comment by fyr77** [comment]
I couldn't find a way of detecting the most recent hotfix version. EnvyUpdate therefore will only alert when new "stable" drivers are released. 
It will not alert because of a "new" driver version when using a newer driver than detected online.
