### ISSUE TITLE
Publish on choco/scoop/winget

### ISSUE THREAD

**Issue by fyr77** [fyr77/EnvyUpdate#20]
Publishing EnvyUpdate to chocolatey/scoop/winget would be nice for easier installation.

**Comment by fyr77** [comment]
For now I will focus on Chocolatey and Scoop, since WinGet [does not yet support](https://github.com/microsoft/winget-cli/issues/182) "portable" applications

**Comment by fyr77** [comment]
Scoop rejected my submission to the `extras` bucket because of the small project size and the lack of reputable maintainers, which I can fully understand. I will instead add the manifest to this repository for manual installation.

Chocolatey is quite a bit more involved, therefore I decided not to use it.

**Comment by KraXen72** [comment]
Hi, i have seen many small projects on scoop/extras - could you please attempt to publish the version 3.x there again? i can only find version 2.x under some 3-rd party buckets, which is not ideal. Thanks!

**Comment by fyr77** [comment]
I will keep this in mind, but I will wait for now until I know how Nvidia continues with their new app, see #41.

**Comment by KraXen72** [comment]
ahh okay. thanks for the info. hopefully their change doesen't yield too much work!
