### ISSUE TITLE
An option to ignore the current driver and not send any more notifications for it would be great.

### ISSUE THREAD

**Issue by jonjbm** [fyr77/EnvyUpdate#24]
Hey, first off thank you so much for this program. It's been integral to my goal of slimming down my task manager and installed programs (which included removing GeForce Experience).

One small issue I've come across is when there is a new driver version available that I would prefer to skip, but I keep getting notifications popping up regularly about it. It would be great if there were a button or check box somewhere which gave the option "ignore this version".

I don't want to stop notifications entirely -- usually I _do_ get the most recent driver, so I want to continue getting notifications about new ones. The issue is that sometimes certain drivers are reported to not do so well in benchmarks, so I'd prefer to skip them (this is currently true with 512.15). The button/check box I had in mind would basically turn off notifications _until_ the next version is detected.

**Comment by fyr77** [comment]
That's a good suggestion. I'll see to implement it when I find the time.

**Comment by fyr77** [comment]
Alright, implemented in commit 25fa94144b70302021d462ae4ba7ba3c49230597 and version 2.13
