### ISSUE TITLE
Update local driver version periodically

### ISSUE THREAD

**Issue by Xaeroxe** [fyr77/EnvyUpdate#27]
I'd like `Util.GetLocDriv` to get called occasionally without having to relaunch the program. Ideally we'd hook this to an event for a new program getting installed (Maybe through [`ManagementEventWatcher`](https://learn.microsoft.com/en-us/dotnet/api/system.management.managementeventwatcher?view=dotnet-plat-ext-7.0)?)

If an event driven model wouldn't work, then it should run once every few hours, with the ability to manually trigger it via a "Refresh" button.

**Comment by fyr77** [comment]
That is a great idea. I'll get to it as soon as I can.

**Comment by fyr77** [comment]
I added a `FileSystemWatcher` to watch `Program Files\NVIDIA Corporation\Installer2\InstallerCore` for changes. I hope this works, time will tell. Commit 1b8e59cf1469d7229acd706ad1d851a1c213f3c2.

**Comment by fyr77** [comment]
This will be included in the next update, closing this issue for now. In case it doesn't work properly, feel free to reopen it.

**Comment by fyr77** [comment]
Nevermind, something is crashing it now. Reopening.

**Comment by fyr77** [comment]
Alright, it should work now. Please let me know of any issues.

**Comment by Xaeroxe** [comment]
Worked great when I tested it just now, thanks!
