### ISSUE TITLE
Invalid API response from NVIDIA.

### ISSUE THREAD

**Issue by Fen0MeN102** [fyr77/EnvyUpdate#29]
An "Invalid API response from NVIDIA" problem occurs if you choose the "Studio" option while your card doesn't have any studio drivers available. After that, the program can't be started without deleting its settings file.

![image](https://user-images.githubusercontent.com/69432581/212467652-f1d5b044-4ee5-40ae-8e08-cd1ac4d24349.png)

**Comment by fyr77** [comment]
I see the problem. I never check if the card actually supports the driver type selected. Shouldn't be too hard to fix, thank you for the heads-up!

**Comment by GillesJ97** [comment]
Where is this setting file please ?

**Comment by GillesJ97** [comment]
Thank you, I already deleted it but it didn't fix the bug.

**Comment by GillesJ97** [comment]
GTX 1060 maxQ with game ready driver

**Comment by GillesJ97** [comment]
but don't worry i will wait patiently for a fix ;)

**Comment by fyr77** [comment]
> GTX 1060 maxQ with game ready driver

Oh, that is strange. Can you post a screenshot of EnvyUpdate on your computer?

**Comment by fyr77** [comment]
This should be fixed in 2e4fa930ff5e1fb89d96c451f24e1e36eee6ec10
