### ISSUE TITLE
Support Quadro

### ISSUE THREAD

**Issue by fyr77** [fyr77/EnvyUpdate#30]
Quadro GPUs have a different version system. Would be nice if EnvyUpdate supported those as well.

**Comment by fyr77** [comment]
I have no way of testing and investigating Quadro cards. I will close this issue for now, if anyone else can implement or test this, feel free to reopen.

**Comment by fyr77** [comment]
I have decided to reopen this issue as a form of "to-do", since I would quite like to support more than just Geforce.

**Comment by Ecchigo123** [comment]
I have a Quadro P2000 and could help out with some logs and tests from Mo - Fr when I have time.

**Comment by Klohger** [comment]
Oh, so that's why this program has problems on my installation. 
I'd be happy to help.

**Comment by fyr77** [comment]
I do not have the resources to implement this, therefore I will close this issue again. If anyone wants to implement it in my stead pull requests are welcome.
