### ISSUE TITLE
FATAL Driver installer config not found, terminating.

### ISSUE THREAD

**Issue by JohannesIBK** [fyr77/EnvyUpdate#38]
When I try to install the Nvidia Driver, it aborts due to a missing config file.

It creates a `[version]-extracted` folder, but it is empty.

[envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/13692221/envyupdate.log)

**Comment by fyr77** [comment]
I will try to have a look tomorrow. In the meantime, could you try deleting the downloaded installer.exe file and restart envyupdate to have it redownload the driver files? @JohannesIBK

**Comment by JohannesIBK** [comment]
I've tried deleting the appdata folder and use the current directory instead the appdata option, but its always the same.

**Comment by fyr77** [comment]
It always uses the app data folder? Do you have write access to the directory envyupdate.exe is in? 

What's the path of envyupdate.exe on your machine?

**Comment by JohannesIBK** [comment]
I've kept the executable in the Downloads folder. 

For the data, I've tried using the appdata folder and the local folder (Downloads), but it's always the same outcome. It downloads it successfully and creates the `[version]-extracted` folder, but the folder is always empty.

**Comment by JohannesIBK** [comment]
I've found the error, my username contains a space (`C:/Zero Dawn/...`)

**Comment by JohannesIBK** [comment]
I've created a PR for this issue, but I never used C# before, so no idea if there is a better way to solve this

**Comment by fyr77** [comment]
Wonderful, thank you! Looks good to me, merged.
Will create a minor release fixing this asap.
