### ISSUE TITLE
[Question] What does it all install / update?

### ISSUE THREAD

**Issue by Senliast** [fyr77/EnvyUpdate#40]
I couldnt find the answer in README, therefore i wanted to ask here. Which all components of driver does it install? For example, i dont have GeForce Experience installed and would not like to install it. Will it install it together with driver? Will it update the other components of driver, like FrameView SKD, HD Sound Driver and nVidia System Software?

Thank you.

**Comment by fyr77** [comment]
EnvyUpdate installs all driver components EXCEPT GeForce Experience. This means all drivers like the Shield Controller driver are installed, but everything that is part of or depends on GFE is not installed.

The exact components are:

- Display.Driver
- Display.Nview
- Display.Optimus
- HDAudi
- MSVCR
- NVI2
- NVPCF
- PhysX
- PPC
- ShieldWirelessController

Only applicable software is installed, e.g. on desktop computers Optimus is not installed (I think)

**Comment by Senliast** [comment]
All right, thank you!
