### ISSUE TITLE
Invalid API response from NVIDIA

### ISSUE THREAD

**Issue by LOuroboros** [fyr77/EnvyUpdate#42]
The program doesn't work on my end. It opens a gray square and this error prompt shows up.

![EnvyUpdate_20240223_074044458](https://github.com/fyr77/EnvyUpdate/assets/4485172/73322997-b648-4147-ae2f-ca65998ea824)

I'm using the v3.3 downloaded 5 minutes ago from the Releases tab, Windows 11 v22H2 (Build 22621.2283) and my GPU is a GT 1030 manufactured by GIGABYTE.

Tbh, I don't have the intention of updating my drivers just yet since I already did it a few days ago, I just wanted to check if the program was working at all.

**Comment by LOuroboros** [comment]
> Does it immediately show this when starting up?

Yup.

> If it is possible, enable logging to file in the options and attach it here. Otherwise, create a file called `envyupdate.log` next to the EnvyUpdate.exe file, this also enables logging.

Here you go:  [envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/14389320/envyupdate.log)

**Comment by fyr77** [comment]
I just released 3.4, which should fix your issue. Please try with that.

Thanks for reporting it, I am surprised no one noticed that until now.

**Comment by LOuroboros** [comment]
Well, there's certainly a difference between v3.3 and v3.4.

Now on v3.4 the program opens *(still as a gray block)*, something seems to be happening in the background, and then the program just closes abruptly after a few seconds.

https://github.com/fyr77/EnvyUpdate/assets/4485172/6446c4c6-7491-47b1-94e1-cca44926bed9

Here's a log: [envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/14392637/envyupdate.log)

**Comment by fyr77** [comment]
@LOuroboros Interesting, it crashes when attempting to show the notification. Could you try running this debug build? Extract all files in the zip please.
[EnvyUpdate-Debug-3.4.zip](https://github.com/fyr77/EnvyUpdate/files/14392814/EnvyUpdate-Debug-3.4.zip)

**Comment by fyr77** [comment]
@LOuroboros I have added an exception handler around the notification code. Please try [this build](https://github.com/fyr77/EnvyUpdate/files/14392836/EnvyUpdate-Debug.zip) instead if possible.

**Comment by LOuroboros** [comment]
> @LOuroboros I have added an exception handler around the notification code. Please try [this build](https://github.com/fyr77/EnvyUpdate/files/14392836/EnvyUpdate-Debug.zip) instead if possible.

I tried this version directly, and at a glance, it seems to work 🥳 

https://github.com/fyr77/EnvyUpdate/assets/4485172/48758697-e813-4e3b-b725-8032798b1260

I doubt it's needed, but here's the log I generated preemptively when I ran the program just in case: [envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/14396610/envyupdate.log)

**Comment by fyr77** [comment]
Interesting, according to the Log "The notification platform is unavailable." - I did not know this was possible. Have you disable Windows notifications in some manner? @LOuroboros 

I'll push this error handler in the next update in a few minutes.

**Comment by LOuroboros** [comment]
> Have you disable Windows notifications in some manner?

Yes. I tend to disable components and features that I know I will not make use of at all 😅

**Comment by fyr77** [comment]
That's fair. Thanks for the info and the bug report, I find it surprising that no one reported that so far since it must have been there for quite a while. Closing this issue :)
