### ISSUE TITLE
Invalid API response from Nvidia | Quadro T1000

### ISSUE THREAD

**Issue by H3ADROOM** [fyr77/EnvyUpdate#45]
I've tried to use your program today, but I've encountered this error:
![image](https://github.com/fyr77/EnvyUpdate/assets/61066950/ad32dc13-e1a3-4100-9ac6-dc0866d89a96)

**Comment by fyr77** [comment]
Hi, unfortunately EnvyUpdate does not support Quadro cards, since they use a different driver versioning system. Sorry to disappoint you, but I fear you have to find something else...
