### ISSUE TITLE
Update loop with 560.70

### ISSUE THREAD

**Issue by jathek** [fyr77/EnvyUpdate#49]
Seems to be update looping on Windows 11 Pro 23H2 22631.3880 when trying to install driver 560.70. I downloaded and hit install, and when it returned to EnvyUpdate, I was immediately notified about the same update. The old driver is still the one installed. Seems like the driver install is crashing and EnvyUpdate doesn't notice? I was able to run the 560.70 driver installer manually and it installed successfully.

![image](https://github.com/user-attachments/assets/5654f7cb-2f86-406a-ada3-1da5fa6386a5)

**Comment by fyr77** [comment]
Oh, maybe they actually changed the format now. I am not home for the next few days, but I will investigate asap.

**Comment by jathek** [comment]
Some more info, fwiw:
- I only saw this problem with two Windows 11 machines. My Windows 10 machine was able to update fine.
- On both the W11 machines, I was running as a normal user, and put in the admin account password when necessary when the installer asked for elevation
- On the W10 machine, I was running as the admin user and just hit "yes" when asked for elevation.

**Comment by fyr77** [comment]
Oh, weird. I did just check on my laptop - the driver structure looks normal to me. Did you use EnvyUpdate successfully before on the W11 machines? @jathek

**Comment by jathek** [comment]
Yes, the previous driver was installed fine with EnvyUpdate. I will keep an eye out the next time a driver is pushed. Maybe it was a Windows fluke?

**Comment by fyr77** [comment]
Unfortunately I was unable to replicate the issue on my machine... Did it work for you after the second attempt or is it "stuck"? @jathek

**Comment by jathek** [comment]
It was stuck and didn't work. I installed the driver manually by running the downloaded exe, and afterwards EnvyUpdate detected that the new driver was installed. I will see if it happens again when the next driver update happens.

**Comment by jathek** [comment]
Following up on this. Driver version 560.81 released recently, and I was able to update to it with EnvyUpdate on a W10 machine (bare metal) and two different W11 machines (VMs). So I think it was some odd crash or bug specific to 560.70. Going to close this as a fluke, for now.
