### ISSUE TITLE
EnvyUpdate doesn't work with RTX A2000 12GB

### ISSUE THREAD

**Issue by nmelay** [fyr77/EnvyUpdate#50]
I've just replaced my GeForce GTX 1650 with an RTX A2000 12GB, and EnvyUpdate stopped working.

![image](https://github.com/user-attachments/assets/43565f7c-c196-4d49-9f71-da5f47badb41)

It's trying to find a new driver at `http://www.nvidia.com/Download/processDriver.aspx?psid=1&pfid=8&osid=57&dtcid=1&dtid=1`

The NVIDIA driver finder queries `https://www.nvidia.com/Download/processFind.aspx?psid=122&pfid=971&osid=57&lid=12&whql=1&lang=en-us&ctk=0&qnfslb=10&dtcid=1` instead.

So it appears EnvyUpdate can't determine the appropriate psid and pfid for this card.

**Comment by fyr77** [comment]
Hi!

Unfortunately, EnvyUpdate does not support Quadro cards at all, since they have a different version system then GeForce. I do not have the time to implement this or the hardware to test it with, so this will not be added by me in the foreseeable future. 

Sorry...

**Comment by nmelay** [comment]
Hi,

That's OK, I saw your similar comment on the Quadro T1000 issue from [H3ADROOM](https://github.com/H3ADROOM) just after I opened mine.
It would be nice for EnvyUpdate to fail with a nicer message though, such as "No supported GPU found. EnvyUpdate only supports NVIDIA GeForce GPUs" or something like this.

Anyway, EnvyUpdate worked fine while I was using a GeForce 1650... so thanks for this!

**Comment by fyr77** [comment]
That is a good point, a nicer message is certainly advantageous. I'll write it down.
